---

- name: Enforce cgroups limit on falco
  command: >
    systemctl set-property falco.service
      CPUQuota={{ falco_cgroups_cpuquota | default('60%') }}
      MemoryLimit={{ falco_cgroups_memorylimit | default('1G') }}
      CPUShares={{ falco_cgroups_cpushares | default('1024') }}
  args:
    creates: /etc/systemd/system/falco.slice.d/50-CPUQuota.conf
