---

- name: add draios key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present
  register: pkg_result
  until: pkg_result is success
  become: yes
- name: install draios apt source
  get_url:
    url: http://download.draios.com/stable/deb/draios.list
    dest: /etc/apt/sources.list.d/draios.list
    mode: 0444
    #checksum: 'sha256:e9e2ed7d6f02607d855cfe14ef3d37eb13bdb75cecb735b93f12c9af6693185f'
  become: yes

## to ensure gcc available for dkms
- include: gcc.yml

- name: apt | kernel headers install
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: apt | falco install
  apt:
    name: "{{ falco_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
  become: yes
