---
- name: Provision AMI
  hosts: all
  vars:
    additional_ntp_servers: ["169.254.169.123"]
    nomad_version: "0.10.0"
    nomad_module_version: "v0.5.0"
    consul_module_version: "v0.7.3"
    consul_version: "1.6.1"
    docker_version: "18.06.0~ce~3-0~ubuntu"
    vault_version: "1.2.3"
    vault_module_url: "https://github.com/hashicorp/terraform-aws-vault.git"
    vault_module_version: "v0.13.3"
    consul_enable_syslog: true
    nomad_enable_syslog: true
    td_agent_config_file: ""
    td_agent_config_vars_file: ""
    td_agent_config_dest_file: "/etc/td-agent/td-agent.conf"
    ca_certificate: ""
    consul_host: ""
    consul_port: 443
    consul_scheme: https
    consul_token: ""
    consul_integration_prefix: "terraform/"
    nomad_additional_config: []
    netshare_version: 0.36
    docker_enable_efs: false
    timezone: "Asia/Singapore"
    falco_slack_output_webhook: ""
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install CA Certificate
    include_tasks: "{{ playbook_dir }}/../../../../tasks/include_role_checked.yml"
    vars:
      role: "{{ playbook_dir }}/../../../../roles/ansible-ca-store"
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate != ""
  - name: Install Vault PKI CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/vault-pki"
  - name: Install chrony
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/chrony"
  - name: Install td-agent
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/td-agent"
    vars:
      config_file: "{{ td_agent_config_file }}"
      config_vars_file: "{{ td_agent_config_vars_file }}"
      config_dest_file: "{{ td_agent_config_dest_file }}"
  - name: Install Telegraf
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/telegraf"
  - name: Install pip3
    apt:
      name: python3-pip
    become: yes
  - name: Install Docker Volume Netshare
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/docker-volume-netshare"
    when: docker_enable_efs
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/consul"
    vars:
      consul_client_address: "127.0.0.1 169.254.1.1"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-vault"
  - name: Install Nomad
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/nomad"
  - name: Install Docker and Docker Compose
    include_tasks: "{{ playbook_dir }}/../../../../tasks/include_role_checked.yml"
    vars:
      role: "{{ playbook_dir }}/../../../../roles/ansible-docker-ubuntu"
  - name: Use DNSMasq as default Docker Daemon DNS server
    copy:
      content: '{ "dns": ["169.254.1.1"] }'
      dest: /etc/docker/daemon.json
      owner: root
    become: yes
  - name: Install Vault SSH Configuration Script
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-ssh-script"
  - name: Set default timezone
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/timezone"
  - name: Install Falco 
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-falco"
  - name: Harden the server
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/server-hardening"
